outToml = "AutoToml_Ratios/02_03_2023/ModelRatio/sigma12_3fl_udc_cool_double_Neg"
massCSV = "mass_sysErr.csv"
nameMod = "ModelRatio"

[cfuns]
cfDirBase = "correlators/NTx32/data/sigma12.3fl_udc/"
cfListBase = "correlators/NTx32/lists/sigma12.3fl.udc-sX.list"
NT = [ "128", "128", "64", "56", "48",]
T0NT = "128"
cshifts = [ 0, 1, 2, 3, 4, 5, 6, 7,]
hadronType = "baryon"
norm = "post:src"
cfSkip = [ "STRINGNOTIN",]
cfCut = 100000
operators = [ "sigma12.3fl",]
quarks = [ "udc",]
hadrons = "Sigma_{c}(udc)"
cfLabels = [ "sigma12_3fl_udc_128s0", "sigma12_3fl_udc_128s1", "sigma12_3fl_udc_128s2", "sigma12_3fl_udc_128s3", "sigma12_3fl_udc_128s4", "sigma12_3fl_udc_128s5", "sigma12_3fl_udc_128s6", "sigma12_3fl_udc_128s7", "sigma12_3fl_udc_128s0", "sigma12_3fl_udc_128s1", "sigma12_3fl_udc_128s2", "sigma12_3fl_udc_128s3", "sigma12_3fl_udc_128s4", "sigma12_3fl_udc_128s5", "sigma12_3fl_udc_128s6", "sigma12_3fl_udc_128s7", "sigma12_3fl_udc_64s0", "sigma12_3fl_udc_64s1", "sigma12_3fl_udc_64s2", "sigma12_3fl_udc_64s3", "sigma12_3fl_udc_64s4", "sigma12_3fl_udc_64s5", "sigma12_3fl_udc_64s6", "sigma12_3fl_udc_64s7", "sigma12_3fl_udc_56s0", "sigma12_3fl_udc_56s1", "sigma12_3fl_udc_56s2", "sigma12_3fl_udc_56s3", "sigma12_3fl_udc_56s4", "sigma12_3fl_udc_56s5", "sigma12_3fl_udc_56s6", "sigma12_3fl_udc_56s7", "sigma12_3fl_udc_48s0", "sigma12_3fl_udc_48s1", "sigma12_3fl_udc_48s2", "sigma12_3fl_udc_48s3", "sigma12_3fl_udc_48s4", "sigma12_3fl_udc_48s5", "sigma12_3fl_udc_48s6", "sigma12_3fl_udc_48s7",]

[maths]
averageCShift = true
single = false
double = true
G = false
negParity = true

[analysis]
RxLim = [ "None", "None",]
RyLim = [ 0, 1,]
RCurves = [ 4, 0, 1, 2, 3, 5, 6,]
RXPoints = [ 47.5, 94.99, 108.56, 126.65, 151.99, 168.87, 189.98, 217.12, 253.31, 303.97, 379.96,]
anaDir = "output/ratios/02_03_2023/sigma12_3fl_udc/cool/double/Neg"
src_t0 = 0
GxLim = [ "None", "None",]
GyLim = [ "None", "None",]
xStart = 1
symMathLabels = [ "sigma12_3fl_udc_128", "F_sigma12_3fl_udc_128", "sigma12_3fl_udc_128", "F_sigma12_3fl_udc_128", "sigma12_3fl_udc_64", "F_sigma12_3fl_udc_64", "sigma12_3fl_udc_56", "F_sigma12_3fl_udc_56", "sigma12_3fl_udc_48", "F_sigma12_3fl_udc_48", "Model_sigma12_3fl_udc_128_128", "F_Model_sigma12_3fl_udc_128_128", "Ratio_sigma12_3fl_udc_128_128", "F_Ratio_sigma12_3fl_udc_128_128", "Ratio_sigma12_3fl_udc_128_128_128", "F_Ratio_sigma12_3fl_udc_128_128_128", "Double_sigma12_3fl_udc_128_128", "F_Double_sigma12_3fl_udc_128_128", "Model_sigma12_3fl_udc_64_64", "F_Model_sigma12_3fl_udc_64_64", "Ratio_sigma12_3fl_udc_64_64", "F_Ratio_sigma12_3fl_udc_64_64", "Ratio_sigma12_3fl_udc_64_64_128", "F_Ratio_sigma12_3fl_udc_64_64_128", "Double_sigma12_3fl_udc_64_128", "F_Double_sigma12_3fl_udc_64_128", "Model_sigma12_3fl_udc_56_56", "F_Model_sigma12_3fl_udc_56_56", "Ratio_sigma12_3fl_udc_56_56", "F_Ratio_sigma12_3fl_udc_56_56", "Ratio_sigma12_3fl_udc_56_56_128", "F_Ratio_sigma12_3fl_udc_56_56_128", "Double_sigma12_3fl_udc_56_128", "F_Double_sigma12_3fl_udc_56_128", "Model_sigma12_3fl_udc_48_48", "F_Model_sigma12_3fl_udc_48_48", "Ratio_sigma12_3fl_udc_48_48", "F_Ratio_sigma12_3fl_udc_48_48", "Ratio_sigma12_3fl_udc_48_48_128", "F_Ratio_sigma12_3fl_udc_48_48_128", "Double_sigma12_3fl_udc_48_128", "F_Double_sigma12_3fl_udc_48_128",]
symMathMaths = [ "M:sigma12_3fl_udc_128s0,sigma12_3fl_udc_128s1,sigma12_3fl_udc_128s2,sigma12_3fl_udc_128s3,sigma12_3fl_udc_128s4,sigma12_3fl_udc_128s5,sigma12_3fl_udc_128s6,sigma12_3fl_udc_128s7:(sigma12_3fl_udc_128s0+sigma12_3fl_udc_128s1+sigma12_3fl_udc_128s2+sigma12_3fl_udc_128s3+sigma12_3fl_udc_128s4+sigma12_3fl_udc_128s5+sigma12_3fl_udc_128s6+sigma12_3fl_udc_128s7)/8", "flip:sigma12_3fl_udc_128:sigma12_3fl_udc_128", "M:sigma12_3fl_udc_128s0,sigma12_3fl_udc_128s1,sigma12_3fl_udc_128s2,sigma12_3fl_udc_128s3,sigma12_3fl_udc_128s4,sigma12_3fl_udc_128s5,sigma12_3fl_udc_128s6,sigma12_3fl_udc_128s7:(sigma12_3fl_udc_128s0+sigma12_3fl_udc_128s1+sigma12_3fl_udc_128s2+sigma12_3fl_udc_128s3+sigma12_3fl_udc_128s4+sigma12_3fl_udc_128s5+sigma12_3fl_udc_128s6+sigma12_3fl_udc_128s7)/8", "flip:sigma12_3fl_udc_128:sigma12_3fl_udc_128", "M:sigma12_3fl_udc_64s0,sigma12_3fl_udc_64s1,sigma12_3fl_udc_64s2,sigma12_3fl_udc_64s3,sigma12_3fl_udc_64s4,sigma12_3fl_udc_64s5,sigma12_3fl_udc_64s6,sigma12_3fl_udc_64s7:(sigma12_3fl_udc_64s0+sigma12_3fl_udc_64s1+sigma12_3fl_udc_64s2+sigma12_3fl_udc_64s3+sigma12_3fl_udc_64s4+sigma12_3fl_udc_64s5+sigma12_3fl_udc_64s6+sigma12_3fl_udc_64s7)/8", "flip:sigma12_3fl_udc_64:sigma12_3fl_udc_64", "M:sigma12_3fl_udc_56s0,sigma12_3fl_udc_56s1,sigma12_3fl_udc_56s2,sigma12_3fl_udc_56s3,sigma12_3fl_udc_56s4,sigma12_3fl_udc_56s5,sigma12_3fl_udc_56s6,sigma12_3fl_udc_56s7:(sigma12_3fl_udc_56s0+sigma12_3fl_udc_56s1+sigma12_3fl_udc_56s2+sigma12_3fl_udc_56s3+sigma12_3fl_udc_56s4+sigma12_3fl_udc_56s5+sigma12_3fl_udc_56s6+sigma12_3fl_udc_56s7)/8", "flip:sigma12_3fl_udc_56:sigma12_3fl_udc_56", "M:sigma12_3fl_udc_48s0,sigma12_3fl_udc_48s1,sigma12_3fl_udc_48s2,sigma12_3fl_udc_48s3,sigma12_3fl_udc_48s4,sigma12_3fl_udc_48s5,sigma12_3fl_udc_48s6,sigma12_3fl_udc_48s7:(sigma12_3fl_udc_48s0+sigma12_3fl_udc_48s1+sigma12_3fl_udc_48s2+sigma12_3fl_udc_48s3+sigma12_3fl_udc_48s4+sigma12_3fl_udc_48s5+sigma12_3fl_udc_48s6+sigma12_3fl_udc_48s7)/8", "flip:sigma12_3fl_udc_48:sigma12_3fl_udc_48", "toy:baryon:[1.0(0),1.0(0)]_[0.41178(58),0.4777(50)]_128_0_128", "flip:Model_sigma12_3fl_udc_128_128:Model_sigma12_3fl_udc_128_128", "M:sigma12_3fl_udc_128,Model_sigma12_3fl_udc_128_128:Model_sigma12_3fl_udc_128_128/sigma12_3fl_udc_128", "flip:Ratio_sigma12_3fl_udc_128_128:Ratio_sigma12_3fl_udc_128_128", "ext:Ratio_sigma12_3fl_udc_128_128:128_min_end", "ext:F_Ratio_sigma12_3fl_udc_128_128:128_min_end", "M:Ratio_sigma12_3fl_udc_128_128_128,Ratio_sigma12_3fl_udc_128_128:Ratio_sigma12_3fl_udc_128_128_128/Ratio_sigma12_3fl_udc_128_128", "M:F_Ratio_sigma12_3fl_udc_128_128_128,F_Ratio_sigma12_3fl_udc_128_128:F_Ratio_sigma12_3fl_udc_128_128_128/F_Ratio_sigma12_3fl_udc_128_128", "toy:baryon:[1.0(0),1.0(0)]_[0.41178(58),0.4777(50)]_64_0_64", "flip:Model_sigma12_3fl_udc_64_64:Model_sigma12_3fl_udc_64_64", "M:sigma12_3fl_udc_64,Model_sigma12_3fl_udc_64_64:Model_sigma12_3fl_udc_64_64/sigma12_3fl_udc_64", "flip:Ratio_sigma12_3fl_udc_64_64:Ratio_sigma12_3fl_udc_64_64", "ext:Ratio_sigma12_3fl_udc_64_64:128_min_end", "ext:F_Ratio_sigma12_3fl_udc_64_64:128_min_end", "M:Ratio_sigma12_3fl_udc_64_64_128,Ratio_sigma12_3fl_udc_128_128:Ratio_sigma12_3fl_udc_64_64_128/Ratio_sigma12_3fl_udc_128_128", "M:F_Ratio_sigma12_3fl_udc_64_64_128,F_Ratio_sigma12_3fl_udc_128_128:F_Ratio_sigma12_3fl_udc_64_64_128/F_Ratio_sigma12_3fl_udc_128_128", "toy:baryon:[1.0(0),1.0(0)]_[0.41178(58),0.4777(50)]_56_0_56", "flip:Model_sigma12_3fl_udc_56_56:Model_sigma12_3fl_udc_56_56", "M:sigma12_3fl_udc_56,Model_sigma12_3fl_udc_56_56:Model_sigma12_3fl_udc_56_56/sigma12_3fl_udc_56", "flip:Ratio_sigma12_3fl_udc_56_56:Ratio_sigma12_3fl_udc_56_56", "ext:Ratio_sigma12_3fl_udc_56_56:128_min_end", "ext:F_Ratio_sigma12_3fl_udc_56_56:128_min_end", "M:Ratio_sigma12_3fl_udc_56_56_128,Ratio_sigma12_3fl_udc_128_128:Ratio_sigma12_3fl_udc_56_56_128/Ratio_sigma12_3fl_udc_128_128", "M:F_Ratio_sigma12_3fl_udc_56_56_128,F_Ratio_sigma12_3fl_udc_128_128:F_Ratio_sigma12_3fl_udc_56_56_128/F_Ratio_sigma12_3fl_udc_128_128", "toy:baryon:[1.0(0),1.0(0)]_[0.41178(58),0.4777(50)]_48_0_48", "flip:Model_sigma12_3fl_udc_48_48:Model_sigma12_3fl_udc_48_48", "M:sigma12_3fl_udc_48,Model_sigma12_3fl_udc_48_48:Model_sigma12_3fl_udc_48_48/sigma12_3fl_udc_48", "flip:Ratio_sigma12_3fl_udc_48_48:Ratio_sigma12_3fl_udc_48_48", "ext:Ratio_sigma12_3fl_udc_48_48:128_min_end", "ext:F_Ratio_sigma12_3fl_udc_48_48:128_min_end", "M:Ratio_sigma12_3fl_udc_48_48_128,Ratio_sigma12_3fl_udc_128_128:Ratio_sigma12_3fl_udc_48_48_128/Ratio_sigma12_3fl_udc_128_128", "M:F_Ratio_sigma12_3fl_udc_48_48_128,F_Ratio_sigma12_3fl_udc_128_128:F_Ratio_sigma12_3fl_udc_48_48_128/F_Ratio_sigma12_3fl_udc_128_128",]
labelsToAnalyse = [ "F_Double_sigma12_3fl_udc_128_128", "F_Double_sigma12_3fl_udc_64_128", "F_Double_sigma12_3fl_udc_56_128", "F_Double_sigma12_3fl_udc_48_128",]
labelsToPlot = [ "$N_\\tau = 128$", "$N_\\tau = 64$", "$N_\\tau = 56$", "$N_\\tau = 48$",]
xMins = [ "F_Model_sigma12_3fl_udc_128_128", "F_Model_sigma12_3fl_udc_64_64", "F_Model_sigma12_3fl_udc_56_56", "F_Model_sigma12_3fl_udc_48_48",]
ylabel = "$R(\\tau;T;T_0)$"

[cfuns.sigma12_3fl_udc_128s0]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s0.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s1]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s1.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s2]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s2.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s3]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s3.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s4]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s4.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s5]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s5.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s6]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s6.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s7]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s7.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_64s0]
cfDir = "correlators/64x32/data/sigma12.3fl_udc/"
cfList = "correlators/64x32/lists/sigma12.3fl.udc-s0.list"
latt = 64
ext = ""

[cfuns.sigma12_3fl_udc_64s1]
cfDir = "correlators/64x32/data/sigma12.3fl_udc/"
cfList = "correlators/64x32/lists/sigma12.3fl.udc-s1.list"
latt = 64
ext = ""

[cfuns.sigma12_3fl_udc_64s2]
cfDir = "correlators/64x32/data/sigma12.3fl_udc/"
cfList = "correlators/64x32/lists/sigma12.3fl.udc-s2.list"
latt = 64
ext = ""

[cfuns.sigma12_3fl_udc_64s3]
cfDir = "correlators/64x32/data/sigma12.3fl_udc/"
cfList = "correlators/64x32/lists/sigma12.3fl.udc-s3.list"
latt = 64
ext = ""

[cfuns.sigma12_3fl_udc_64s4]
cfDir = "correlators/64x32/data/sigma12.3fl_udc/"
cfList = "correlators/64x32/lists/sigma12.3fl.udc-s4.list"
latt = 64
ext = ""

[cfuns.sigma12_3fl_udc_64s5]
cfDir = "correlators/64x32/data/sigma12.3fl_udc/"
cfList = "correlators/64x32/lists/sigma12.3fl.udc-s5.list"
latt = 64
ext = ""

[cfuns.sigma12_3fl_udc_64s6]
cfDir = "correlators/64x32/data/sigma12.3fl_udc/"
cfList = "correlators/64x32/lists/sigma12.3fl.udc-s6.list"
latt = 64
ext = ""

[cfuns.sigma12_3fl_udc_64s7]
cfDir = "correlators/64x32/data/sigma12.3fl_udc/"
cfList = "correlators/64x32/lists/sigma12.3fl.udc-s7.list"
latt = 64
ext = ""

[cfuns.sigma12_3fl_udc_56s0]
cfDir = "correlators/56x32/data/sigma12.3fl_udc/"
cfList = "correlators/56x32/lists/sigma12.3fl.udc-s0.list"
latt = 56
ext = ""

[cfuns.sigma12_3fl_udc_56s1]
cfDir = "correlators/56x32/data/sigma12.3fl_udc/"
cfList = "correlators/56x32/lists/sigma12.3fl.udc-s1.list"
latt = 56
ext = ""

[cfuns.sigma12_3fl_udc_56s2]
cfDir = "correlators/56x32/data/sigma12.3fl_udc/"
cfList = "correlators/56x32/lists/sigma12.3fl.udc-s2.list"
latt = 56
ext = ""

[cfuns.sigma12_3fl_udc_56s3]
cfDir = "correlators/56x32/data/sigma12.3fl_udc/"
cfList = "correlators/56x32/lists/sigma12.3fl.udc-s3.list"
latt = 56
ext = ""

[cfuns.sigma12_3fl_udc_56s4]
cfDir = "correlators/56x32/data/sigma12.3fl_udc/"
cfList = "correlators/56x32/lists/sigma12.3fl.udc-s4.list"
latt = 56
ext = ""

[cfuns.sigma12_3fl_udc_56s5]
cfDir = "correlators/56x32/data/sigma12.3fl_udc/"
cfList = "correlators/56x32/lists/sigma12.3fl.udc-s5.list"
latt = 56
ext = ""

[cfuns.sigma12_3fl_udc_56s6]
cfDir = "correlators/56x32/data/sigma12.3fl_udc/"
cfList = "correlators/56x32/lists/sigma12.3fl.udc-s6.list"
latt = 56
ext = ""

[cfuns.sigma12_3fl_udc_56s7]
cfDir = "correlators/56x32/data/sigma12.3fl_udc/"
cfList = "correlators/56x32/lists/sigma12.3fl.udc-s7.list"
latt = 56
ext = ""

[cfuns.sigma12_3fl_udc_48s0]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s0.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s1]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s1.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s2]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s2.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s3]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s3.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s4]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s4.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s5]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s5.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s6]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s6.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s7]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s7.list"
latt = 48
ext = ""
