outToml = "AutoToml_Ratios/02_03_2023/ModelRatio/sigma12_3fl_udc_mid_single_Pos"
massCSV = "mass_sysErr.csv"
nameMod = "ModelRatio"

[cfuns]
cfDirBase = "correlators/NTx32/data/sigma12.3fl_udc/"
cfListBase = "correlators/NTx32/lists/sigma12.3fl.udc-sX.list"
NT = [ "128", "48", "40", "36", "32",]
T0NT = "128"
cshifts = [ 0, 1, 2, 3, 4, 5, 6, 7,]
hadronType = "baryon"
norm = "post:src"
cfSkip = [ "STRINGNOTIN",]
cfCut = 100000
operators = [ "sigma12.3fl",]
quarks = [ "udc",]
hadrons = "Sigma_{c}(udc)"
cfLabels = [ "sigma12_3fl_udc_128s0", "sigma12_3fl_udc_128s1", "sigma12_3fl_udc_128s2", "sigma12_3fl_udc_128s3", "sigma12_3fl_udc_128s4", "sigma12_3fl_udc_128s5", "sigma12_3fl_udc_128s6", "sigma12_3fl_udc_128s7", "sigma12_3fl_udc_48s0", "sigma12_3fl_udc_48s1", "sigma12_3fl_udc_48s2", "sigma12_3fl_udc_48s3", "sigma12_3fl_udc_48s4", "sigma12_3fl_udc_48s5", "sigma12_3fl_udc_48s6", "sigma12_3fl_udc_48s7", "sigma12_3fl_udc_40s0", "sigma12_3fl_udc_40s1", "sigma12_3fl_udc_40s2", "sigma12_3fl_udc_40s3", "sigma12_3fl_udc_40s4", "sigma12_3fl_udc_40s5", "sigma12_3fl_udc_40s6", "sigma12_3fl_udc_40s7", "sigma12_3fl_udc_36s0", "sigma12_3fl_udc_36s1", "sigma12_3fl_udc_36s2", "sigma12_3fl_udc_36s3", "sigma12_3fl_udc_36s4", "sigma12_3fl_udc_36s5", "sigma12_3fl_udc_36s6", "sigma12_3fl_udc_36s7", "sigma12_3fl_udc_32s0", "sigma12_3fl_udc_32s1", "sigma12_3fl_udc_32s2", "sigma12_3fl_udc_32s3", "sigma12_3fl_udc_32s4", "sigma12_3fl_udc_32s5", "sigma12_3fl_udc_32s6", "sigma12_3fl_udc_32s7",]

[maths]
averageCShift = true
single = true
double = false
G = false
negParity = false

[analysis]
RxLim = [ "None", "None",]
RyLim = [ 0, 1,]
RCurves = [ 4, 0, 1, 2, 3, 5, 6,]
RXPoints = [ 47.5, 94.99, 108.56, 126.65, 151.99, 168.87, 189.98, 217.12, 253.31, 303.97, 379.96,]
anaDir = "output/ratios/02_03_2023/sigma12_3fl_udc/mid/single/Pos"
src_t0 = 0
GxLim = [ "None", "None",]
GyLim = [ 0.125,3.25]
xStart = 1
symMathLabels = [ "sigma12_3fl_udc_128", "sigma12_3fl_udc_48", "sigma12_3fl_udc_40", "sigma12_3fl_udc_36", "sigma12_3fl_udc_32", "Model_sigma12_3fl_udc_48_48", "Ratio_sigma12_3fl_udc_48_48", "Ratio_sigma12_3fl_udc_48_48_128", "Model_sigma12_3fl_udc_40_40", "Ratio_sigma12_3fl_udc_40_40", "Ratio_sigma12_3fl_udc_40_40_128", "Model_sigma12_3fl_udc_36_36", "Ratio_sigma12_3fl_udc_36_36", "Ratio_sigma12_3fl_udc_36_36_128", "Model_sigma12_3fl_udc_32_32", "Ratio_sigma12_3fl_udc_32_32", "Ratio_sigma12_3fl_udc_32_32_128",]
symMathMaths = [ "M:sigma12_3fl_udc_128s0,sigma12_3fl_udc_128s1,sigma12_3fl_udc_128s2,sigma12_3fl_udc_128s3,sigma12_3fl_udc_128s4,sigma12_3fl_udc_128s5,sigma12_3fl_udc_128s6,sigma12_3fl_udc_128s7:(sigma12_3fl_udc_128s0+sigma12_3fl_udc_128s1+sigma12_3fl_udc_128s2+sigma12_3fl_udc_128s3+sigma12_3fl_udc_128s4+sigma12_3fl_udc_128s5+sigma12_3fl_udc_128s6+sigma12_3fl_udc_128s7)/8", "M:sigma12_3fl_udc_48s0,sigma12_3fl_udc_48s1,sigma12_3fl_udc_48s2,sigma12_3fl_udc_48s3,sigma12_3fl_udc_48s4,sigma12_3fl_udc_48s5,sigma12_3fl_udc_48s6,sigma12_3fl_udc_48s7:(sigma12_3fl_udc_48s0+sigma12_3fl_udc_48s1+sigma12_3fl_udc_48s2+sigma12_3fl_udc_48s3+sigma12_3fl_udc_48s4+sigma12_3fl_udc_48s5+sigma12_3fl_udc_48s6+sigma12_3fl_udc_48s7)/8", "M:sigma12_3fl_udc_40s0,sigma12_3fl_udc_40s1,sigma12_3fl_udc_40s2,sigma12_3fl_udc_40s3,sigma12_3fl_udc_40s4,sigma12_3fl_udc_40s5,sigma12_3fl_udc_40s6,sigma12_3fl_udc_40s7:(sigma12_3fl_udc_40s0+sigma12_3fl_udc_40s1+sigma12_3fl_udc_40s2+sigma12_3fl_udc_40s3+sigma12_3fl_udc_40s4+sigma12_3fl_udc_40s5+sigma12_3fl_udc_40s6+sigma12_3fl_udc_40s7)/8", "M:sigma12_3fl_udc_36s0,sigma12_3fl_udc_36s1,sigma12_3fl_udc_36s2,sigma12_3fl_udc_36s3,sigma12_3fl_udc_36s4,sigma12_3fl_udc_36s5,sigma12_3fl_udc_36s6,sigma12_3fl_udc_36s7:(sigma12_3fl_udc_36s0+sigma12_3fl_udc_36s1+sigma12_3fl_udc_36s2+sigma12_3fl_udc_36s3+sigma12_3fl_udc_36s4+sigma12_3fl_udc_36s5+sigma12_3fl_udc_36s6+sigma12_3fl_udc_36s7)/8", "M:sigma12_3fl_udc_32s0,sigma12_3fl_udc_32s1,sigma12_3fl_udc_32s2,sigma12_3fl_udc_32s3,sigma12_3fl_udc_32s4,sigma12_3fl_udc_32s5,sigma12_3fl_udc_32s6,sigma12_3fl_udc_32s7:(sigma12_3fl_udc_32s0+sigma12_3fl_udc_32s1+sigma12_3fl_udc_32s2+sigma12_3fl_udc_32s3+sigma12_3fl_udc_32s4+sigma12_3fl_udc_32s5+sigma12_3fl_udc_32s6+sigma12_3fl_udc_32s7)/8", "toy:baryon:[1.0(0),1.0(0)]_[0.41178(58),0.4777(50)]_48_0_48", "M:sigma12_3fl_udc_48,Model_sigma12_3fl_udc_48_48:Model_sigma12_3fl_udc_48_48/sigma12_3fl_udc_48", "ext:Ratio_sigma12_3fl_udc_48_48:128_min_end", "toy:baryon:[1.0(0),1.0(0)]_[0.41178(58),0.4777(50)]_40_0_40", "M:sigma12_3fl_udc_40,Model_sigma12_3fl_udc_40_40:Model_sigma12_3fl_udc_40_40/sigma12_3fl_udc_40", "ext:Ratio_sigma12_3fl_udc_40_40:128_min_end", "toy:baryon:[1.0(0),1.0(0)]_[0.41178(58),0.4777(50)]_36_0_36", "M:sigma12_3fl_udc_36,Model_sigma12_3fl_udc_36_36:Model_sigma12_3fl_udc_36_36/sigma12_3fl_udc_36", "ext:Ratio_sigma12_3fl_udc_36_36:128_min_end", "toy:baryon:[1.0(0),1.0(0)]_[0.41178(58),0.4777(50)]_32_0_32", "M:sigma12_3fl_udc_32,Model_sigma12_3fl_udc_32_32:Model_sigma12_3fl_udc_32_32/sigma12_3fl_udc_32", "ext:Ratio_sigma12_3fl_udc_32_32:128_min_end",]
labelsToAnalyse = [ "Ratio_sigma12_3fl_udc_48_48", "Ratio_sigma12_3fl_udc_40_40", "Ratio_sigma12_3fl_udc_36_36", "Ratio_sigma12_3fl_udc_32_32",]
labelsToPlot = [ "$N_\\tau = 48$", "$N_\\tau = 40$", "$N_\\tau = 36$", "$N_\\tau = 32$",]
xMins = [ "sigma12_3fl_udc_48", "sigma12_3fl_udc_40", "sigma12_3fl_udc_36", "sigma12_3fl_udc_32",]
ylabel = "$r(\\tau;T;T_0)$"

[cfuns.sigma12_3fl_udc_128s0]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s0.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s1]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s1.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s2]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s2.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s3]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s3.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s4]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s4.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s5]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s5.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s6]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s6.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_128s7]
cfDir = "correlators/128x32/data/sigma12.3fl_udc/"
cfList = "correlators/128x32/lists/sigma12.3fl.udc-s7.list"
latt = 128
ext = ""

[cfuns.sigma12_3fl_udc_48s0]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s0.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s1]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s1.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s2]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s2.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s3]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s3.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s4]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s4.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s5]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s5.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s6]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s6.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_48s7]
cfDir = "correlators/48x32/data/sigma12.3fl_udc/"
cfList = "correlators/48x32/lists/sigma12.3fl.udc-s7.list"
latt = 48
ext = ""

[cfuns.sigma12_3fl_udc_40s0]
cfDir = "correlators/40x32/data/sigma12.3fl_udc/"
cfList = "correlators/40x32/lists/sigma12.3fl.udc-s0.list"
latt = 40
ext = ""

[cfuns.sigma12_3fl_udc_40s1]
cfDir = "correlators/40x32/data/sigma12.3fl_udc/"
cfList = "correlators/40x32/lists/sigma12.3fl.udc-s1.list"
latt = 40
ext = ""

[cfuns.sigma12_3fl_udc_40s2]
cfDir = "correlators/40x32/data/sigma12.3fl_udc/"
cfList = "correlators/40x32/lists/sigma12.3fl.udc-s2.list"
latt = 40
ext = ""

[cfuns.sigma12_3fl_udc_40s3]
cfDir = "correlators/40x32/data/sigma12.3fl_udc/"
cfList = "correlators/40x32/lists/sigma12.3fl.udc-s3.list"
latt = 40
ext = ""

[cfuns.sigma12_3fl_udc_40s4]
cfDir = "correlators/40x32/data/sigma12.3fl_udc/"
cfList = "correlators/40x32/lists/sigma12.3fl.udc-s4.list"
latt = 40
ext = ""

[cfuns.sigma12_3fl_udc_40s5]
cfDir = "correlators/40x32/data/sigma12.3fl_udc/"
cfList = "correlators/40x32/lists/sigma12.3fl.udc-s5.list"
latt = 40
ext = ""

[cfuns.sigma12_3fl_udc_40s6]
cfDir = "correlators/40x32/data/sigma12.3fl_udc/"
cfList = "correlators/40x32/lists/sigma12.3fl.udc-s6.list"
latt = 40
ext = ""

[cfuns.sigma12_3fl_udc_40s7]
cfDir = "correlators/40x32/data/sigma12.3fl_udc/"
cfList = "correlators/40x32/lists/sigma12.3fl.udc-s7.list"
latt = 40
ext = ""

[cfuns.sigma12_3fl_udc_36s0]
cfDir = "correlators/36x32/data/sigma12.3fl_udc/"
cfList = "correlators/36x32/lists/sigma12.3fl.udc-s0.list"
latt = 36
ext = ""

[cfuns.sigma12_3fl_udc_36s1]
cfDir = "correlators/36x32/data/sigma12.3fl_udc/"
cfList = "correlators/36x32/lists/sigma12.3fl.udc-s1.list"
latt = 36
ext = ""

[cfuns.sigma12_3fl_udc_36s2]
cfDir = "correlators/36x32/data/sigma12.3fl_udc/"
cfList = "correlators/36x32/lists/sigma12.3fl.udc-s2.list"
latt = 36
ext = ""

[cfuns.sigma12_3fl_udc_36s3]
cfDir = "correlators/36x32/data/sigma12.3fl_udc/"
cfList = "correlators/36x32/lists/sigma12.3fl.udc-s3.list"
latt = 36
ext = ""

[cfuns.sigma12_3fl_udc_36s4]
cfDir = "correlators/36x32/data/sigma12.3fl_udc/"
cfList = "correlators/36x32/lists/sigma12.3fl.udc-s4.list"
latt = 36
ext = ""

[cfuns.sigma12_3fl_udc_36s5]
cfDir = "correlators/36x32/data/sigma12.3fl_udc/"
cfList = "correlators/36x32/lists/sigma12.3fl.udc-s5.list"
latt = 36
ext = ""

[cfuns.sigma12_3fl_udc_36s6]
cfDir = "correlators/36x32/data/sigma12.3fl_udc/"
cfList = "correlators/36x32/lists/sigma12.3fl.udc-s6.list"
latt = 36
ext = ""

[cfuns.sigma12_3fl_udc_36s7]
cfDir = "correlators/36x32/data/sigma12.3fl_udc/"
cfList = "correlators/36x32/lists/sigma12.3fl.udc-s7.list"
latt = 36
ext = ""

[cfuns.sigma12_3fl_udc_32s0]
cfDir = "correlators/32x32/data/sigma12.3fl_udc/"
cfList = "correlators/32x32/lists/sigma12.3fl.udc-s0.list"
latt = 32
ext = ""

[cfuns.sigma12_3fl_udc_32s1]
cfDir = "correlators/32x32/data/sigma12.3fl_udc/"
cfList = "correlators/32x32/lists/sigma12.3fl.udc-s1.list"
latt = 32
ext = ""

[cfuns.sigma12_3fl_udc_32s2]
cfDir = "correlators/32x32/data/sigma12.3fl_udc/"
cfList = "correlators/32x32/lists/sigma12.3fl.udc-s2.list"
latt = 32
ext = ""

[cfuns.sigma12_3fl_udc_32s3]
cfDir = "correlators/32x32/data/sigma12.3fl_udc/"
cfList = "correlators/32x32/lists/sigma12.3fl.udc-s3.list"
latt = 32
ext = ""

[cfuns.sigma12_3fl_udc_32s4]
cfDir = "correlators/32x32/data/sigma12.3fl_udc/"
cfList = "correlators/32x32/lists/sigma12.3fl.udc-s4.list"
latt = 32
ext = ""

[cfuns.sigma12_3fl_udc_32s5]
cfDir = "correlators/32x32/data/sigma12.3fl_udc/"
cfList = "correlators/32x32/lists/sigma12.3fl.udc-s5.list"
latt = 32
ext = ""

[cfuns.sigma12_3fl_udc_32s6]
cfDir = "correlators/32x32/data/sigma12.3fl_udc/"
cfList = "correlators/32x32/lists/sigma12.3fl.udc-s6.list"
latt = 32
ext = ""

[cfuns.sigma12_3fl_udc_32s7]
cfDir = "correlators/32x32/data/sigma12.3fl_udc/"
cfList = "correlators/32x32/lists/sigma12.3fl.udc-s7.list"
latt = 32
ext = ""
