name: charm
channels:
  - defaults
dependencies:
  - python=3.11.4
  - numpy=1.25.0
  - matplotlib=3.7.1
  - pandas=1.5.3
  - typing=3.10.0.0
  - scipy=1.10.1
  - pip=23.1.2
  - mypy=0.981
  - sympy=1.11.1
  - toml=0.10.2
  - poppler=22.12.0
  - opt_einsum=3.3.0
  - cython0.29.35
  - pip:
     - lsqfit==13.0.1
     - gvar==11.11.2
     - types-toml==0.10.8.7
