name: charm
channels:
  - defaults
dependencies:
  - python=3.8.13
  - numpy=1.22.3
  - matplotlib=3.5.2
  - pandas=1.4.3
  - typing=3.10.0.0
  - scipy=1.7.3
  - pip=22.1.2
  - mypy==0.910
  - sympy=1.10.1
  - toml=0.10.2
  - poppler=21.11.0
  - opt_einsum=3.3.0
  - pip:
     - lsqfit==12.0.3
     - gvar==11.10.1
     - types-toml==0.10.8
